### ISSUE TITLE
there is a glitch in the front-end that only displays at certain monitor widths, please fix

### ISSUE THREAD

**Issue by JoshuaVSherman** [UltimatePromotions/ourhandsandfeet#106]
![glitch](https://cloud.githubusercontent.com/assets/13340120/21293560/31bdca70-c4f6-11e6-8d0b-c61a9dadaa12.png)

**Comment by TheR3dErik** [comment]
At what widths does this glitch happen? I have been unable to reproduce it so far..

**Comment by JoshuaVSherman** [comment]
On my laptop

**Comment by JoshuaVSherman** [comment]
@TheR3dErik hey Erik, if you are stuck on how to fix this, maybe reach out to @joshstoro 
Josh Storo and see if he can have a hangout screen share with you please.
