### ISSUE TITLE
Create a Google doc draft for the  "About" page in the team's Drive folder

### ISSUE THREAD

**Issue by JoshuaVSherman** [UltimatePromotions/ourhandsandfeet#11]
Acceptance Criteria:

* please be sure to include the following:
 - How to donate (either your time if you are a web developer or your money to help pay for the development/maintenance of the app
- that your donations are NOT tax deductible (since we are not a non-profit status)
- a section for Thank You to Our Sponsors

**Comment by JoshuaVSherman** [comment]
@JerryMcarter @chemmom2 
This is the task for the about page
I am only expecting a draft to be in the Drive folder by end of day this Saturday please

**Comment by JoshuaVSherman** [comment]
@JerryMcarter @chemmom2 Mrs Sherman (Maria) is going to work on the About page today, so Jeremiah does not need to work on it anymore. Thanks

**Comment by chemmom2** [comment]
@JoshuaVSherman Draft is available for review. I would like to put the list of donors on the News page for now, since there are currently only three sections on the About page and I have used all three, plus there is not much news at the moment.
