### ISSUE TITLE
Weird error when trying to start frontend

### ISSUE THREAD

**Issue by TheR3dErik** [UltimatePromotions/ourhandsandfeet#111]
I get an odd error in the console when attempting to start the frontend. I have included a screenshot of it below:

![screen shot 2017-01-01 at 7 12 54 pm](https://cloud.githubusercontent.com/assets/20156870/21583630/a6d1d394-d057-11e6-85cf-900fa1883b9c.png)

**Comment by JoshuaVSherman** [comment]
@TheR3dErik 
please delete your node_modules and do a 
yarn install
then bower install
then
npm run build:prod
npm run server:prod

let me know, I think maybe you didn't get the updated modules installed from the last time I updated the front-end skeleton webpack stuff.

**Comment by JoshuaVSherman** [comment]
@TheR3dErik 
let me know if this is resolved now
