### ISSUE TITLE
When user type set, redirect to appropriate dashboard

### ISSUE THREAD

**Issue by joshstoro** [UltimatePromotions/ourhandsandfeet#141]
Create two new dashboards for our user types. Redirect to these if the new user has finished the initial account settings page.

**Comment by JoshuaVSherman** [comment]
@joshstoro 
I believe the functionality i'm looking for is
the side navigation should show Dashboard, but when the CharityManager clicks the menu link, they are presented with /dashboard/charity
if they are loggin into the app, and they have set their user type = charitymanager
if they log into the app and they have not set their user type yet, then they should be presented with the
/dashboard route only, which requests them to provide the additional user information first
after they click the Update button, then they are redirected to /dashboard/charity 
if that is the user type the chose. i'm going to update the sys requirements document in our google drive folder. Call or ping me if you need more information. Thanks
This comment is probably several tasks that can be broken out and put into the ZenHub board if you want to work on those also.
