### ISSUE TITLE
Write unit tests to cover dashboard-routes/dashboard.js (front-end)

### ISSUE THREAD

**Issue by JoshuaVSherman** [UltimatePromotions/ourhandsandfeet#186]

**Comment by freethlua** [comment]
It seems there's two main ways to test aurelia components

The official way: http://aurelia.io/hub.html#/doc/article/aurelia/testing/latest/testing-components 
```js
import {StageComponent} from 'aurelia-testing';
``` 

Example projects: [\[1\]][1] [\[2\]][2]

Another way: http://patrickwalters.net/unit-testing-your-es6-view-models-my-best-practices-for-aurelia/
```js
import {Container} from 'aurelia-dependency-injection';  
import {BehaviorInstance} from 'aurelia-templating';
```

Will see which works out better. 

[1]: https://github.com/MeirionHughes/aurelia-cli-electron-app/blob/master/spec/unit/menu-control.spec.ts
[2]: https://github.com/genadis/aurelia-mdl/blob/master/test/unit/button.spec.js
