### ISSUE TITLE
Fix the test for "Should load webcomponents-lite.js" and "should load polymer.html" in polymer.spec.js

### ISSUE THREAD

**Issue by JoshuaVSherman** [UltimatePromotions/ourhandsandfeet#248]
I commented out both of the failed test

**Comment by freethlua** [comment]
This is working for me. (already fixed?) 

BTW you may also change `describe` to `xdescribe` or `it` to `xit` [to exclude them](https://jasmine.github.io/2.5/introduction#section-Disabling_Suites), this way they still show up as "skipped"

**Comment by JoshuaVSherman** [comment]
@Coletrane 

Thanks for fixing this. I'm planning on pairing session tomorrow still.
have a great rest of you day.
