### ISSUE TITLE
Update readme file

### ISSUE THREAD

**Issue by JoshuaVSherman** [UltimatePromotions/ourhandsandfeet#39]

**Comment by JoshuaVSherman** [comment]
* how to get the app running should be explained in the readme file (for any new developer)

**Comment by JoshuaVSherman** [comment]
it should provide high level steps to get things running with a link to the detailed google document for more information on getting started

**Comment by TheR3dErik** [comment]
I'm not sure if you would classify this as "done" yet, but it's better.

**Comment by JoshuaVSherman** [comment]
The read me file has been updated for the front-end codebase. Please update the backend readme file (be sure to explain the .env file that is needed and how it needs to be modified depending on if you are running the front end in development or production mode) - ask Josh if you don't know this information
