### ISSUE TITLE
Write a test in the front end to verify that all Polymer components have loaded

### ISSUE THREAD

**Issue by JoshuaVSherman** [UltimatePromotions/ourhandsandfeet#80]
When the app starts, expect that all Polymer components have loaded (this can be viewed from the Google Console). Write an automated test in the front end to confirm.

**Comment by JoshuaVSherman** [comment]
@Coletrane 
Two pass, one fails, i'm commenting it out for now. we can talk about it tomorrow in scrum if you are available.
thanks,
![image](https://cloud.githubusercontent.com/assets/13340120/22207248/63a4c2ba-e14c-11e6-8555-8d8563214792.png)

**Comment by Coletrane** [comment]
Hmm, it worked on my machine. Ill take another look at it. I will be
available at scrum tomorrow.

**Comment by JoshuaVSherman** [comment]
You can also check the build in circleci
