### ISSUE TITLE
write unit tests for OurHandsAndFeetBackend/auth/ google.js

### ISSUE THREAD

**Issue by JoshuaVSherman** [UltimatePromotions/ourhandsandfeet#90]

**Comment by JoshuaVSherman** [comment]
@Coletrane hello, if you can't get this done,  please let me know. If I don't hear from you by next week (Sunday) on this task, I will go ahead and do this with another developer. Thank you

**Comment by Coletrane** [comment]
@JoshuaVSherman go ahead and put someone else on this issue. I've put quite a bit of time into it, but im still not sure if its correct or even testing anything.

**Comment by JoshuaVSherman** [comment]
Ok we can talk tonight and get you working on something else, no prob. I
hope you did learn a bit about mock and fake servers

**Comment by Coletrane** [comment]
Yes I did! What time do you want to chat?

**Comment by JoshuaVSherman** [comment]
8pm please
