### ISSUE TITLE
move coverage folder to generate inside the test folder - backend tests

### ISSUE THREAD

**Issue by JoshuaVSherman** [UltimatePromotions/ourhandsandfeet#96]

**Comment by TheR3dErik** [comment]
Okay, I've figured this out. In the package.json, at the line that reads `"test": "istanbul cover ./node_modules/.bin/_mocha test/**/*.js --coverage"`, you need to append ` --dir ./test/coverage` after `--coverage`. Do you want me to make a commit and merge my branch for this?

**Comment by JoshuaVSherman** [comment]
Awesome!

On Dec 27, 2016 9:20 PM, "TheR3dErik" <notifications@github.com> wrote:

Okay, I've figured this out. In the package.json, at the line that
reads "test":
"istanbul cover ./node_modules/.bin/_mocha test/**/*.js --coverage", you
need to append --dir ./test/coverage after --coverage. Do you want me to
make a commit and merge my branch for this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/UltimatePromotions/ourhandsandfeet/issues/96#issuecomment-269414229>,
or mute the thread

**Comment by JoshuaVSherman** [comment]
Yes, please commit to you branch and pull request
